#!/home/rana/.local/bin/zestc

                                    *=/(1F.qX08Y08:chemistry_field[L1])
                                              |
                                              N    ribcage.xb
                                              |
                          *=/(1O.qX04Y04:oxytocin[L1])---E---*=/(1D.qX12Y04:dopamine[L1])

absorb 2_chemical.rana
absorb chemistry_field.rana
absorb oxytocin.rana
absorb dopamine.rana
absorb ribcage.xb
